### ISSUE TITLE
Some Combinations of Co-Occurring Biotic Classes Are Not Expected/Realistic

### ISSUE THREAD

**Issue by cybersea** [orcoastalmgmt/cmecs#42]
It makes sense that there are co-occurring (in the same polygon) elements from Biotic Classes 2.2 (Faunal Bed) and 2.5 (Aquatic Bed).   But, it is not likely (although not impossible) that these classes would co-occur or overlap with the wetlands Biotic classes (2.6, 2.7, 2.8).   Perhaps this can be used a  validation cross-check. 
For example: 
(BC_CLASS02 = '2.2' or BC_CLASS05 = '2.5') and BC_CLASS08 = '2.8'

**Comment by tchaddad** [comment]
It's less about validation, and more about temporal differences in the landscape. For the purposes of the hard copy maps we will provide to planners, we will resolve this conflict. But for the full data set, we will show the discrepancies.

**Comment by tchaddad** [comment]
We were asked a question about how this conflict was resolved in the hard copy maps, and I realized I should have recorded the answer here in case others find this issue. 

Conflicts in the hard copy map cartography were resolved in favor of higher numbered classes, in all cases except for one (oysters). So for example if 2.8 and 2.5 overlap, the tie breaks in favor of 2.8. Oysters were the exception to the rule simply because they were already super rare in our data, and so we wanted them to appear whenever we had them documented. They also are only in the data set in Coos Bay, so they are already somewhat of an exception. We can revisit this in the future if we are lucky enough to come into more comprehensive oyster data.
